# Site settings
title: raulperula
email: raules@gmail.com
url: http://raulperula.github.io
phone: +34
description: "Personal website of Raúl Pérula-Martínez, Software Engineer and Roboticist. He works at the Social Robots Group at RoboticsLab, University Carlos III, Madrid, Spain."
owner: Raúl Pérula-Martínez
aboutA: "Personal website of Raúl Pérula-Martínez, Software Engineer and Roboticist. He works at the Social Robots Group at RoboticsLab, University Carlos III, Madrid, Spain."
aboutB: "Raúl has a 5-year research experience in software and robotics engineering, working full time with Maggie, one of the most advanced social robots out there. He is mainly working on software engineering applied to robotics and decision-making systems. His deep knowledge of C++ and Python as well as the ROS framework has been mainly used for driver implementation, high level skills development, and artificial intelligence."
blog: "This is a (not so) secret page, and as such you should not be here. In here, I put everything I might find useful for myself. It is not meant to be consulted (and consumed) by others. You might find it useful, though: look around, there might be some good tutorial in here!"
keywords: [Raul,Perula,raules,software,robotics,engineer,researcher,phd,social robot,maggie robot,human robot interaction,asrob,ieee]

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://www.linkedin.com/in/raulpm
  - title: github
    url: https://github.com/raulperula
  - title: twitter
    url: https://twitter.com/ra_ules
  - title: google-plus
    url: https://plus.google.com/+RaulPM

# Postal address (add as many lines as necessary)
address:
  - line: University Carlos III of Madrid,
  - line: Department of System Engineering and Automation,
  - line: Leganes, 28911, Madrid, Spain.

# Build settings
markdown: kramdown
permalink: pretty
gems:
  - jekyll-sitemap

# Some more default colors
# 
color:
# Color settings (hex-codes without the leading hash-tag)
# I've put different combinations to test
# 
# ALTERNATIVE 0
  articletext: 4e4e4e                     # This is the text color
  primary: b5c0c7                         # This is the gray color with a blue tint
  secondary: 84ad52                       # This is the green color
  secondary-dark: 6e9145                  # This is the dark green color
  secondary-alpha: rgba(132,173,82,.7)    # This is the same as the secondary color but with an alpha value
  tertiary: e20e59                        # These are the pink accents
# ALTERNATIVE 1
  # primary: b4b4b4                         # This is gray
  # secondary: ca6558                       # This is reddish
  # secondary-dark: b9493b                  # This is reddish
  # tertiary: 8ca08d                        # This is greenish
# ALTERNATIVE 2
  #secondary: 589ee4                       # This is blueish
  #secondary-dark: 368ade                  # This is blueish
  tertiary: 52b3d9                        # This is light brown
# ALTERNATIVE 3
  # tertiary: 53c3cb                        # This is greenish
  # secondary: f4676d                       # This is reddish
  # secondary-dark: f24e55                  # This is reddish
