# Site settings
title: estheracosta
email: e.acostacumplido@gmail.com
url: http://estherac.github.io
phone: +34
description: "Web personal de Esther Acosta Cumplido, Bióloga especializada en Virología Humana. Actualmente en búsqueda activa de trabajo, Madrid, España."
owner: Esther Acosta Cumplido
aboutA: "Web personal de Esther Acosta Cumplido, Bióloga especializada en Virología Humana. Actualmente en búsqueda activa de trabajo, Madrid, España."
aboutB: "Esther tiene experiencia..."
blog: ""
keywords: [Esther Acosta,estherac,biologia,virologia,investigacion,phd]

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/esther-acosta-cumplido/
  - title: github
    url: https://github.com/estherac
  - title: twitter
    url: https://twitter.com/acosta_cumplido

# Postal address (add as many lines as necessary)
address:
  - line: Madrid, Spain

# Build settings
markdown: kramdown
permalink: pretty
gems:
  - jekyll-sitemap

# Some more default colors
# 
color:
# Color settings (hex-codes without the leading hash-tag)
# I've put different combinations to test
# 
# ALTERNATIVE 0
  articletext: 4e4e4e                     # This is the text color
  primary: 9ad2e4                         # This is the gray color with a green tint
  secondary: 5296ad                       # This is the green color
  secondary-dark: 457e92                  # This is the dark green color
  secondary-alpha: rgba(132,82,173,.7)    # This is the same as the secondary color but with an alpha value
  tertiary: 7a3bff                        # This is purple
